version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  object-detection-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: object-detection-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - minio
    environment:
      MONGO_USER: admin
      MONGO_PASS: admin123
      MONGO_HOST: mongo:27017
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: object-detection

volumes:
  mongo_data:
  minio_data:
