version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "your_redis_password"]
    volumes:
      - redis_data:/data

  object_detection_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - minio
      - redis
    ports:
      - "8000:8000"
    environment:
      MONGO_USER: admin
      MONGO_PASS: admin123
      MONGO_HOST: mongo:27017
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: object-detection
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: your_redis_password
      REDIS_TTL_SECONDS: 3600
    volumes:
      - .:/app

volumes:
  mongo_data:
  minio_data:
  redis_data:
