version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", "your_redis_password"]
    ports:
      - "6379:6379"

  api_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_server
    depends_on:
      - mongo
      - minio
      - redis
    environment:
      MONGO_USER: admin
      MONGO_PASS: admin123
      MONGO_HOST: mongo:27017
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: challenge-2
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: your_redis_password
    ports:
      - "8001:8001"

  nginx:
    image: nginx:latest
    container_name: nginx_cache
    depends_on:
      - api_server
    ports:
      - "8080:8080"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx_cache:/tmp/nginx_cache

volumes:
  mongo_data:
  minio_data:
  nginx_cache:
